FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      gdal-bin \
      libgdal-dev \
      libsndfile1 \
      libbz2-dev \
      liblzma-dev \
      libcurl4-openssl-dev \
      libeccodes-dev \
      ffmpeg \
      curl \
      git \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*
