# Local type stub for ``asyncpg`` (ships no py.typed). Declares exactly the subset
# pirn-core uses: pool creation, pooled/borrowed connections, transactions,
# LISTEN/NOTIFY and records. Column values are driver-decoded and genuinely
# dynamic, so a record hands them out as ``Any``. Extend when new API is used.
from collections.abc import Callable, Generator, Iterable, Iterator, Sequence
from types import TracebackType
from typing import Any


class Record:
    def __getitem__(self, key: str | int, /) -> Any: ...
    def get(self, key: str, default: Any = None, /) -> Any: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[Any]: ...
    def items(self) -> Iterator[tuple[str, Any]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...


class Transaction:
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    async def start(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class Connection:
    async def execute(self, query: str, *args: object, timeout: float | None = None) -> str: ...
    async def executemany(
        self, command: str, args: Iterable[Sequence[object]], *, timeout: float | None = None
    ) -> None: ...
    async def fetch(
        self, query: str, *args: object, timeout: float | None = None
    ) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: object, timeout: float | None = None
    ) -> Record | None: ...
    async def fetchval(
        self, query: str, *args: object, column: int = 0, timeout: float | None = None
    ) -> Any: ...
    def transaction(
        self, *, isolation: str | None = None, readonly: bool = False, deferrable: bool = False
    ) -> Transaction: ...
    async def add_listener(
        self, channel: str, callback: Callable[[Connection, int, str, str], object]
    ) -> None: ...
    async def remove_listener(
        self, channel: str, callback: Callable[[Connection, int, str, str], object]
    ) -> None: ...
    async def close(self, *, timeout: float | None = None) -> None: ...


class PoolAcquireContext:
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    def __await__(self) -> Generator[Any, None, Connection]: ...


class Pool:
    def acquire(self, *, timeout: float | None = None) -> PoolAcquireContext: ...
    async def release(self, connection: Connection, *, timeout: float | None = None) -> None: ...
    async def close(self) -> None: ...
    def terminate(self) -> None: ...
    async def execute(self, query: str, *args: object, timeout: float | None = None) -> str: ...
    async def executemany(
        self, command: str, args: Iterable[Sequence[object]], *, timeout: float | None = None
    ) -> None: ...
    async def fetch(
        self, query: str, *args: object, timeout: float | None = None
    ) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: object, timeout: float | None = None
    ) -> Record | None: ...
    async def fetchval(
        self, query: str, *args: object, column: int = 0, timeout: float | None = None
    ) -> Any: ...
    def __await__(self) -> Generator[Any, None, Pool]: ...


def create_pool(
    dsn: str | None = None,
    *,
    min_size: int = 10,
    max_size: int = 10,
    max_queries: int = 50000,
    max_inactive_connection_lifetime: float = 300.0,
    **connect_kwargs: object,
) -> Pool: ...


async def connect(dsn: str | None = None, **connect_kwargs: object) -> Connection: ...
